name: Build and push image and deploy to aks

on:
  push:
    branches:
      - 'feature/**'
      - 'release/**'
      - 'hotfix/**'
      - main
    tags:
       - '*'
  pull_request:
    branches:
      - main

env:
  PUSH_AND_DEPLOY: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check build step running'
        run: echo build

  deploy-to-test:
    if: contains(github.ref, 'feature/')
    runs-on: ubuntu-latest
    needs: build
    environment: test
    steps:
      - name: 'Check deploy to test step running'
        run: echo deploy to test

  deploy-to-acc:
    if: contains(github.ref, 'release/') || contains(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build
    environment: acc
    steps:
      - name: 'Check deploy to acc step running'
        run: echo deploy to acc

  deploy-to-prod:
    if: contains(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: deploy-to-acc
    environment: prod
    steps:
      - name: 'Check deploy to prod step running'
        run: echo deploy to prod
