name: Test cicd

on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - develop
      - 'release/**'
      - 'hotfix/**'
      - main
    tags:
       - 'v*'
  pull_request:
    branches:
      - main
  release:
    types:
      - published
      - unpublished
      - created
      - edited
      - deleted
      - prereleased
      - released

env:
  PUSH_AND_DEPLOY: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
  GITHUB_CONTEXT: ${{ toJSON(github) }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check build step running'
        run: echo build

      - name: 'Echo github context'
        run: echo "$GITHUB_CONTEXT"

  deploy-to-test:
    if: github.ref_name == 'develop' || contains(github.ref, 'bugfix/')
    runs-on: ubuntu-latest
    needs: build
    environment: test
    steps:
      - name: 'Check deploy to test step running'
        run: echo deploy to test

      - name: 'Deploy to AKS'
        uses: Gemeente-DenHaag/custom-actions/deploy-to-aks@main
        # uses: Gemeente-DenHaag/custom-actions/deploy-to-aks@v0.0.3-dta
        with:
          api-server-url: '${{ secrets.API_SERVER_URL }}'
          sa-secret-name: '${{ secrets.SA_SECRET_NAME }}'
          sa-secret-token: '${{ secrets.SA_SECRET_TOKEN }}'
          release-name: test-new-release
          namespace: dhonline-test
          full-image-url: nginx:latest
          extra-params: '--set name=test-new-release'

  deploy-to-acc:
    if: contains(github.ref, 'release/') || contains(github.ref, 'hotfix/')
    runs-on: ubuntu-latest
    needs: build
    environment: acc
    steps:
      - name: 'Check deploy to acc step running'
        run: echo deploy to acc

  deploy-to-prod:
    if: contains(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: deploy-to-acc
    environment: prod
    steps:
      - name: 'Check deploy to prod step running'
        run: echo deploy to prod
